run-name: Build opencv-contrib-python wheel with non-free features and create PR

on: 
    
    workflow_dispatch:
        inputs:
            branch-to-build:
                description: "Which branch, tag, commit do you want to build and push to ghcr.io:"
                required: true
                type: string
                default: "binder-release"
            
jobs: 

    build-image-and-push:

        runs-on: Ubuntu-24.04
        permissions:
            packages: write
            contents: write
        steps:

            - name: Init Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.9

            - name: Checkout this repo
              uses: actions/checkout@v4
              with:
                ref: ${{inputs.branch-to-build}}
                sparse-checkout: |
                  build/opencv-nonfree/opencv_contrib_python_headless_nonfree-*-linux_x86_64.whl
                  build/ultralytics-non-opencv/ultralytics_non_opencv-*.whl
                  binder/
                  environment.yml
                sparse-checkout-cone-mode: 'false'

            - name: Delete huge unnecessary tools folder
              run: |
                rm -rf /opt/hostedtoolcache
                ls -l

            - name: build and push
              uses: jupyterhub/repo2docker-action@master
              with:
                DOCKER_USERNAME: ${{github.actor}}
                DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
                DOCKER_REGISTRY: "ghcr.io"
                IMAGE_NAME: "gaobobo/opencv-pytorch_machinevision"
                BINDER_CACHE: true
                COMMIT_MSG: "chore: add or update image dependence"
