run-name: Build opencv-contrib-python wheel with non-free features and create PR

on: 
    workflow_dispatch:
        inputs:
            opencv-python-repo-ref:
                description: "Checkout opencv/opencv-python repos' ref, including branch, SHA, tag."
                required: true
                type: string
                default: "4.x"
            
            save-path:
                description: "The path relative this repo that python wheels save to, like build/opencv-nonfree/"
                required: true
                type: string
                default: "build/opencv-nonfree/"

            python-version:
                description: "python version that build environment, like 3.9 or 3.12. This will affect adapted version."
                required: true
                type: string
                default: "3.12"
            
            package-name-suffix:
                description: "Package name's suffix, like opencv-python<SUFFIX>. Recommand start with -, like -nonfree"
                required: false
                type: string
                default: "-nonfree"
            
jobs: 

    build-for-linux:
        strategy:
            matrix:
                build-platform: [ubuntu-24.04, ubuntu-24.04-arm]


        runs-on: ${{matrix.build-platform}}

        permissions:
            actions: write
            contents: write
            pull-requests: write

        env:
            ENABLE_CONTRIB: 1
            ENABLE_HEADLESS: 1
            CMAKE_ARGS: "-DOPENCV_ENABLE_NONFREE=ON"
            PLATFORM: ${{matrix.build-platform}}

        steps:
            - name: Init Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{inputs.python-version}}

            - name: Checkout opencv-python repo
              uses: actions/checkout@v4
              with:
                repository: 'opencv/opencv-python'
                ref: ${{inputs.opencv-python-repo-ref}}
                submodules: true
                path: opencv-python/

            - name: Checkout this repo
              uses: actions/checkout@v4
              with:
                path: main_repo/

            - name: Build opencv-contrib-python-headless
              run: |
                sed -i '91a\    package_name += "${{inputs.package-name-suffix}}"' $GITHUB_WORKSPACE/opencv-python/setup.py
                pip install --upgrade pip
                pip wheel $GITHUB_WORKSPACE/opencv-python/ --verbose -w $GITHUB_WORKSPACE/main_repo/${{inputs.save-path}} --no-deps

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with: 
                add-paths: opencv_*.whl
                path: main_repo/

                branch: actions/opencv-build-${{matrix.build-platform}}
                title: "feat: add OpenCV python wheels with ${{matrix.build-platform}}, adapated Python ${{inputs.python-version}}"
                body: |
                    > [!IMPORTANT]
                    > 
                    > This PR is auto generated by Github Actions.

                    Add OpenCV package for ${{matrix.build-platform}} platform, with non-free package and extra features.
                    
                    To learn more, visit Actions page.
                commit-message: "feat: add OpenCV wheels for ${{matrix.build-platform}} platform"