run-name: Build opencv-contrib-python wheel with non-free features and create PR

on: 
    workflow_dispatch:
        inputs:
            opencv-python-repo-ref:
                description: "Checkout opencv/opencv-python repos' ref, including branch, SHA, tag."
                required: true
                type: string
            
            save-path:
                description: "the path relative this repo that python wheels save to"
                required: true
                type: string
            
jobs: 

    build:
        strategy:
            matrix:
                build-platform: [windows-2025, windows-11-arm]


        runs-on: ${{matrix.build-platform}}

        permissions:
            actions: write
            contents: write
            pull-requests: write

        env:
            ENABLE_CONTRIB: 1
            ENABLE_HEADLESS: 1
            CMAKE_ARGS: "-DOPENCV_ENABLE_NONFREE=ON"
            PLATFORM: ${{matrix.build-platform}}

        steps:
            - name: Checkout opencv-python repo
              uses: actions/checkout@v4
              with:
                repository: 'opencv/opencv-python'
                ref: ${{inputs.opencv-python-repo-ref}}
                submodules: true
                path: opencv-python/

            - name: Checkout this repo
              uses: actions/checkout@v4
              with:
                path: main_repo/

            - name: Build opencv-contrib-python-headless
              run: |
                $REPO_NAME = "gaobobo/opencv-pytorch_MachineVision" -split '/' | Select-Object -Last 1
                pip install --upgrade pip  
                pip wheel "D:/a/${REPO_NAME}/${REPO_NAME}/opencv-python/" -v -w "D:/a/${REPO_NAME}/${REPO_NAME}/main_repo/${{inputs.save-path}}"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with: 
                path: main_repo/
                branch: actions/opencv-build-${{matrix.build-platform}}
                title: "feat: add opencv-contrib-python-headless wheel with ${{matrix.build-platform}}"
                body: |
                    > [!IMPORTANT]
                    > 
                    > This PR is auto generated by Github Actions.

                    Add opencv-contrib-python-headless package for ${{matrix.build-platform}} platform, with non-free package
                    and extra features.
                    
                    To learn more, visit [Actions page](https://github.com/gaobobo/opencv-pytorch_MachineVision/actions/workflows/opencv-nonfree-build_unix.yml).
                commit-message: "feat: add opencv-contrib-python-headless wheel with ${{matrix.build-platform}}"