run-name: Build ultralytics with non-opencv dependence and create PR

on: 
    workflow_dispatch:
        inputs:
            ultralytics-repo-ref:
                description: "Checkout ultralytics/ultralytics repos' ref, including branch, SHA, tag."
                required: true
                type: string
                default: "v8.3.186"
            
            save-path:
                description: "The path relative this repo that python wheels save to, like build/ultralytics-non-opencv/"
                required: true
                type: string
                default: "build/ultralytics-non-opencv/"

            python-version:
                description: "python version that build environment, like 3.9 or 3.12"
                required: true
                type: string
                default: "3.12"
            
jobs: 

    build-for-linux:
        runs-on: ubuntu-24.04

        permissions:
            actions: write
            contents: write
            pull-requests: write

        steps:
            - name: Init Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{inputs.python-version}}

            - name: Checkout ultralytics repo
              uses: actions/checkout@v4
              with:
                repository: 'ultralytics/ultralytics'
                ref: ${{inputs.ultralytics-repo-ref}}
                submodules: true
                path: ultralytics/

            - name: Checkout this repo
              uses: actions/checkout@v4
              with:
                path: main_repo/

            - name: Build ultralytics
              run: |
                sed -i 's/^name = "ultralytics"/name = "ultralytics-non-opencv"/' ultralytics/pyproject.toml
                sed -i '/^[[:space:]]*"opencv-python>=.*",$/d' ultralytics/pyproject.toml
                
                pip install --upgrade pip
                pip wheel ${GITHUB_WORKSPACE}/ultralytics/ --verbose --wheel-dir ${GITHUB_WORKSPACE}/main_repo/${{inputs.save-path}} --no-deps

                ll ${GITHUB_WORKSPACE}/main_repo/${{inputs.save-path}}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with: 
                path: main_repo/
                add-paths: ultralytics-*.whl
                branch: actions/ultralytics-non-opencv
                title: "feat: add ultralytics-non-opencv wheel, adapated Python ${{inputs.python-version}}"
                body: |
                    > [!IMPORTANT]
                    > 
                    > This PR is auto generated by Github Actions.

                    Add ultralytics-non-opencv-build package, , adapated Python ${{inputs.python-version}}"
                    
                    To learn more, visit Actions page.
                commit-message: "feat: add ultralytics-non-opencv wheels"